# Generated by Django 6.0.5 on 2026-05-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_album_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-id']},
        ),
    ]
